[package]
name = "blake3rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "blake3rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
blake3 = { version = "1.3.1", features = ["rayon"] }
libc = "0.2.101"
